# Generated by Django 3.1.7 on 2021-05-01 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=2056)),
                ('image', models.ImageField(upload_to='media')),
                ('date_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date_published')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='myMod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
